<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoBuftest.proto

namespace Proto\Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.Demo.Address</code>
 */
class Address extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string street = 1;</code>
     */
    private $street = '';
    /**
     * Generated from protobuf field <code>int32 number = 2;</code>
     */
    private $number = 0;

    public function __construct() {
        \GPBMetadata\ProtoBuftest::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string street = 1;</code>
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Generated from protobuf field <code>string street = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStreet($var)
    {
        GPBUtil::checkString($var, True);
        $this->street = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number = 2;</code>
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>int32 number = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;

        return $this;
    }

}

