<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoBuftest.proto

namespace Proto\Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Proto.Demo.People</code>
 */
class People extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Proto.Demo.Person person = 1;</code>
     */
    private $person;

    public function __construct() {
        \GPBMetadata\ProtoBuftest::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .Proto.Demo.Person person = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPerson()
    {
        return $this->person;
    }

    /**
     * Generated from protobuf field <code>repeated .Proto.Demo.Person person = 1;</code>
     * @param \Proto\Demo\Person[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPerson($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Demo\Person::class);
        $this->person = $arr;

        return $this;
    }

}

