<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoBuftest.proto

namespace GPBMetadata;

class ProtoBuftest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a1250726f746f427566746573742e70726f746f120a50726f746f" .
            "2e44656d6f222c0a0650656f706c6512220a06706572736f6e1801200328" .
            "0b32122e50726f746f2e44656d6f2e506572736f6e225b0a06506572736f" .
            "6e120c0a046e616d6518012001280912240a076164647265737318022003" .
            "280b32132e50726f746f2e44656d6f2e41646472657373120e0a066d6f62" .
            "696c65180320032809120d0a05656d61696c18042001280922290a074164" .
            "6472657373120e0a06737472656574180120012809120e0a066e756d6265" .
            "72180220012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

